#!/bin/bash

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devpts none /dev/pts

echo "Inside the belly of the beast..."

echo "Avoid problems of languages in GPG keys"
export HOME=/root
export LC_ALL=C
dbus-uuidgen > /var/lib/dbus/machine-id
dpkg-divert --local --rename --add /sbin/initctl
ln -s /bin/true /sbin/initctl

# Customizations
HASPROXY=$(cat /etc/apt/apt.conf | grep "Acquire::http::proxy" | wc -l)
if [ "$HASPROXY" == "1" ]; then
	HTTPPROXY=$(cat /etc/apt/apt.conf | grep "Acquire::http::proxy" | awk '{split($0,a,"\""); print a[2]}')
	HTTPSROXY=$(cat /etc/apt/apt.conf | grep "Acquire::https::proxy" | awk '{split($0,a,"\""); print a[2]}')
	export http_proxy=${HTTPROXY%?};
	export https_proxy=${HTTPSROXY%?};
fi

## Timezone
ln -sf /usr/share/zoneinfo/America/Fortaleza /etc/localtime

## Set Language
locale-gen pt_BR.UTF-8
update-locale LANG=\"pt_BR.UTF-8\" LANGUAGE=\"pt_BR:\"

## Avoid problems with internet
STAT=`grep '#dns=dnsmasq' /etc/NetworkManager/NetworkManager.conf`
if [ "$STAT" == "" ]; then
	sed -i 's/dns=dnsmasq/#dns=dnsmasq/g' /etc/NetworkManager/NetworkManager.conf
	service network-manager restart
	sleep 5
fi

## Remove apps
aptRemove () {
	apt remove --purge $1 -y  2>&1 >/tmp/aptlog
}

aptRemove "kcalc"
aptRemove "qlipper"
aptRemove "noblenote"
aptRemove "trojita"
aptRemove "quassel"
aptRemove "2048-qt"
aptRemove "ark"
# aptRemove "screengrab"

rm -rf /usr/share/applications/info.desktop

## Adding Repositories
dpkg --add-architecture i386

### WinuniX focal repository
wget -qO - https://winunix.github.io/debian/public.key | sudo apt-key add -
sudo add-apt-repository 'deb https://winunix.github.io/debian focal main'

apt-get update >/tmp/aptlog

## upgrade of system
apt-mark hold grub-*
apt-get upgrade -y
apt-mark unhold grub-*

## Install apps
aptInstall () {
	apt install $1 -y 2>&1 >/tmp/aptlog
}

### TTF MS Core Fonts
echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
aptInstall "ttf-mscorefonts-installer"

### Language
aptInstall "language-pack-pt"
aptInstall "language-pack-gnome-pt"
aptInstall "hyphen-pt-pt"
aptInstall "hyphen-pt-br"
aptInstall "hunspell-br"
aptInstall "hunspell-pt-pt"
aptInstall "myspell-pt-br"
aptInstall "mythes-pt-pt"
aptInstall "kde-l10n-ptbr"
aptInstall "wportuguese"
aptInstall "wbrazilian"
aptInstall "language-pack-gnome-br*"
aptInstall "language-pack-br*"

### Appearance
aptInstall "qt5-style-plugin-gtk2"
aptInstall "lubuntu-win10-theme"
aptInstall "lubuntu-win8-cursor-theme"
aptInstall "lubuntu-win10-icon-theme"
aptInstall "lubuntu-win10-qt-theme"
aptInstall "lubuntu-win-theme-apply"

### utils
aptInstall "file-roller"
aptInstall "galculator"
aptInstall "xpad"
aptInstall "gnome-screenshot"
aptInstall "gnome-disk-utility"
aptInstall "gucharmap"
aptInstall "pdfshuffler"
aptInstall "gnome-paint"
aptInstall "audacious"
aptInstall "cheese"

## Apport
sed -i 's/enabled=1/enabled=0/g' /etc/default/apport

## Notifications of update
sed -i '/Prompt=/c\Prompt=never' /etc/update-manager/release-upgrades
sed -i '/APT::Periodic::Update-Package-Lists/c\APT::Periodic::Update-Package-Lists "0";' /etc/apt/apt.conf.d/10periodic

# copying confs from firefox and chrome
rm -rf /root/.config
rm -rf /root/.mozilla
cp -rf /etc/skel/.config /root
cp -rf /etc/skel/.mozilla /root

apt-get autoremove -y
apt-get autoclean -y

## Cleaning chrome environment
rm -rf ~/.bash_history /tmp/*
rm /var/lib/dbus/machine-id
rm /sbin/initctl
rm /root/.wgetrc
rm -rf /root/.config
rm -rf /root/.mozilla
dpkg-divert --rename --remove /sbin/initctl

## Unmount specials files and exiting of chroot
while [ ! -z "$(ls -A /proc)" ]; do
	umount /proc
	umount -lf /proc
	sleep 1
done
while [ ! -z "$(ls -A /sys)" ]; do
	umount /sys
	umount -lf /sys
	sleep 1
done
while [ ! -z "$(ls -A /dev/pts)" ]; do
	umount /dev/pts
	umount -lf /dev/pts
	sleep 1
done
