#!/bin/bash

mount -t proc none /proc
mount -t sysfs none /sys
mount -t devpts none /dev/pts

echo "Inside the belly of the beast..."

# "Avoid problems of languages in GPG keys"
export HOME=/root
export LC_ALL=C
dbus-uuidgen > /var/lib/dbus/machine-id
dpkg-divert --local --rename --add /sbin/initctl
ln -s /bin/true /sbin/initctl

# "Avoid problems with internet"
# STAT=`grep '#dns=dnsmasq' /etc/NetworkManager/NetworkManager.conf`
# if [ "$STAT" == "" ]; then
# 	sed -i 's/dns=dnsmasq/#dns=dnsmasq/g' /etc/NetworkManager/NetworkManager.conf
# 	sudo chmod 644 /etc/NetworkManager/NetworkManager.conf
# 	service network-manager restart
# 	sleep 5
# fi

# Customizations
HASPROXY=$(cat /etc/apt/apt.conf | grep "Acquire::http::proxy" | wc -l)
if [ "$HASPROXY" == "1" ]; then
	HTTPPROXY=$(cat /etc/apt/apt.conf | grep "Acquire::http::proxy" | awk '{split($0,a,"\""); print a[2]}')
	HTTPSROXY=$(cat /etc/apt/apt.conf | grep "Acquire::https::proxy" | awk '{split($0,a,"\""); print a[2]}')
	export http_proxy=${HTTPROXY%?};
	export https_proxy=${HTTPSROXY%?};
fi

# Timezone
ln -sf /usr/share/zoneinfo/America/Fortaleza /etc/localtime

# Set Language
locale-gen pt_BR.UTF-8
update-locale LANG=\"pt_BR.UTF-8\" LANGUAGE=\"pt_BR:\"

# Remove apps
aptRemove () {
	apt remove --purge $1 -y  2>&1 >/tmp/aptlog
}

aptRemove "mtpaint*"
aptRemove "abiword"
aptRemove "gnumeric"
aptRemove "pidgin*"
aptRemove "sylpheed*"
aptRemove "alsamixergui*"
aptRemove "gnome-mpv*"
aptRemove "xfburn"
aptRemove "rdesktop"
aptRemove "usb-creator*"
aptRemove "libabiword*"
aptRemove "libmpv*"
aptRemove "default-jre*"
aptRemove "openjdk-11-jre*"
aptRemove "noblenote"
aptRemove "trojita"
aptRemove "quassel"
aptRemove "2048-qt"
aptRemove "libreoffice-qt5"
aptRemove "qpdfview"
aptRemove "ark"
# aptRemove "software-properties-qt"
# rm -rf /usr/share/applications/info.desktop

# Adding Repositories
dpkg --add-architecture i386

# Get Code Name
codeName=$(cat /etc/lsb-release | grep DISTRIB_CODENAME | cut -d'=' -f2)

# WinuniX focal repository
wget -qO - "https://winunix.github.io/debian/public.key" | sudo apt-key add -
sudo echo "deb https://winunix.github.io/debian $codeName main" > /etc/apt/sources.list.d/winunix-$codeName.list

# AnyDesk all repository
wget -qO - "https://keys.anydesk.com/repos/DEB-GPG-KEY" | sudo apt-key add -
sudo echo "deb http://deb.anydesk.com/ all main" > /etc/apt/sources.list.d/anydesk-stable.list

# Java ppa repository 'sudo add-apt-repository ppa:linuxuprising/java -y'
wget -qO - "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x1cc3d16e460a94ee17fe581cea8cacc073c3db2a" | sudo apt-key add -
sudo echo "deb http://ppa.launchpad.net/linuxuprising/java/ubuntu $codeName main" > /etc/apt/sources.list.d/linuxuprising-ubuntu-java-$codeName.list

# Libreoffice 6.4 repository
if [ "$codeName" == "bionic" ]; then
	sudo add-apt-repository ppa:libreoffice/libreoffice-6-4
fi

## upgrade of system
apt update >/tmp/aptlog
#apt-mark hold grub-*
apt upgrade -y >/tmp/aptlog
#apt-mark unhold grub-*

# Install apps
aptInstall () {
	sudo DEBIAN_FRONTEND=noninteractive apt install $1 -y 2>&1 >/tmp/aptlog
}

# Reconfigure apps
dpkgReconf () {
	sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure $1 2>&1 >/tmp/aptlog
}

# TTF MS Core Fonts
echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections
aptInstall "ttf-mscorefonts-installer"
echo ttf-mscorefonts-installer msttcorefonts/dldir select "/tmp/mscoref" | debconf-set-selections
dpkgReconf "ttf-mscorefonts-installer"

# EFI Deps
aptInstall "grub-efi-amd64-signed"
# aptInstall "grub-efi"

# Language
aptInstall "language-pack-pt"
aptInstall "language-pack-pt-base"
aptInstall "language-pack-gnome-pt"
aptInstall "language-pack-gnome-pt-base"
aptInstall "language-pack-kde-pt"
aptInstall "hyphen-pt-pt"
aptInstall "hyphen-pt-br"
aptInstall "myspell-pt-pt"
aptInstall "myspell-pt-br"
aptInstall "myspell-pt"
aptInstall "hunspell-pt-pt"
aptInstall "hunspell-pt-br"
aptInstall "mythes-pt-pt"
aptInstall "wportuguese"
aptInstall "wbrazilian"
dpkgReconf "locales"

# Appearance Common
aptInstall "fonts-dejavu"
aptInstall "lubuntu-win10-theme"
aptInstall "lubuntu-win10-icon-theme"
aptInstall "lubuntu-win8-cursor-theme"

# Appearance LXQt
aptInstall "qt5-style-plugin-gtk2"
aptInstall "lubuntu-win10-qt-theme"
aptInstall "sddm-theme-win10"

# Java
echo debconf shared/accepted-oracle-license-v1-2 select true | sudo debconf-set-selections
aptInstall "oracle-java16-installer"

# utils
aptInstall "winunix-software-center"
aptInstall "proxy-linux"
aptInstall "lxreset"
aptInstall "gstreamer1.0-plugins-ugly"
aptInstall "gstreamer1.0-plugins-bad"
aptInstall "gstreamer1.0-libav"
aptInstall "rar"
aptInstall "unrar"
aptInstall "p7zip"
aptInstall "p7zip-full"
aptInstall "zenity"
aptInstall "traceroute"
aptInstall "net-tools"
aptInstall "cups"
aptInstall "openssh-server"
aptInstall "libnss3-tools"
aptInstall "apt-transport-https"
aptInstall "libpam-mount"
aptInstall "libpam-gnome-keyring"
aptInstall "smbclient"
aptInstall "samba"
aptInstall "libdvd-pkg"
dpkgReconf "libdvd-pkg"
aptInstall "python3-smbc"
aptInstall "mesa-utils"
aptInstall "xdotool"
aptInstall "xdg-utils"
aptInstall "curl"
aptInstall "graphicsmagick"
aptInstall "blueman"
aptInstall "software-properties-gtk"

# Drivers
aptInstall "bcmwl-kernel-source"
# aptInstall "xsettingsd" Just on 20.04
# aptInstall "xserver-xorg-input-synaptics" Just on 20.04

# Accessories
aptInstall "xpad"
aptInstall "gnome-disk-utility"
aptInstall "cheese"
aptInstall "hardinfo"
aptInstall "gucharmap"

# Apps
aptInstall "file-roller"
aptInstall "firefox"
aptInstall "firefox-locale-pt"
aptInstall "vlc"
aptInstall "gimp"
aptInstall "inkscape"
aptInstall "evince"
aptInstall "kdenlive"
aptInstall "imagination"
aptInstall "libreoffice"
aptInstall "libreoffice-sdbc-hsqldb"
aptInstall "libreoffice-l10n-pt"
aptInstall "libreoffice-l10n-pt-br"
aptInstall "libreoffice-help-pt-br"
aptInstall "openoffice.org-hyphenation"
aptInstall "eog"
aptInstall "flashplugin-installer"
aptInstall "rdesktop"
aptInstall "remmina"
aptInstall "remmina-plugin-rdp"
aptInstall "lsb"
aptInstall "yad"
aptInstall "python-gi"
aptInstall "pdfshuffler"
aptInstall "audacious"
aptInstall "anydesk"
aptInstall "cifs-utils"
aptInstall "nodejs"
aptInstall "npm"
aptInstall "system-config-samba-wx"
aptInstall "fonts-3rd-party"

# Deps
aptInstall "extlinux"
aptInstall "libaudio2"
aptInstall "syslinux"
aptInstall "libu2f-udev"
aptInstall "libqt4-declarative"

# Wine
aptInstall "wine64"
aptInstall "wine32"
aptInstall "wine-stable"

if [ "$codeName" == "bionic" ]; then
	aptInstall "gnome-screenshot"
	aptInstall "winunix-randr"
fi

if [ "$codeName" == "focal" ]; then
	aptInstall "winunix-language-pt-br"
fi

# aptInstall "/tmp/libpng12-0.deb"
# aptInstall "/tmp/rdesktop.deb" # usando xenial pois atual tem bug no winServer2003
# aptInstall "libgtk2.0-0:i386"
# aptInstall "libxft2:i386"
# aptInstall "libxt6:i386"
# Adobe Reader 8
# aptInstall "/tmp/adobeReader.deb"
# aptInstall "gtk2-engines-murrine:i386"
# aptInstall "gtk2-engines-pixbuf:i386"

# Remove default profile
rm -rf /usr/wx-center/profiles/Administrativo.csv
rm -rf /usr/wx-center/profiles/Laboratorio.csv

# Hardinfo icon
cp -f /usr/share/icons/win10-icons/48x48/devices/audio-card.png /usr/share/hardinfo/pixmaps/logo.png

# EoG light theme
if [ "$codeName" == "bionic" ]; then
	EoGName="eog"
else
	EoGName="org.gnome.eog"
fi
sed -i "s#Exec=eog %U#Exec=env GTK_THEME=\"Windows 10 forLxde\" eog %U#g" /usr/share/applications/$EoGName.desktop
sudo chmod 644 /usr/share/applications/$EoGName.desktop

# Check Winunix Apps
chmod +x /usr/bin/verify-winunix

# Services
sudo systemctl disable anydesk.service
sudo systemctl disable sshd.service

# Notifications of update
if [ "$codeName" == "bionic" ]; then
	sed -i '/Prompt=/c\Prompt=never' /etc/update-manager/release-upgrades
	sudo chmod 644 /etc/update-manager/release-upgrades
	sed -i '/APT::Periodic::Update-Package-Lists/c\APT::Periodic::Update-Package-Lists "0";' /etc/apt/apt.conf.d/10periodic
	sudo chmod 644 /etc/apt/apt.conf.d/10periodic
fi

## Fix Libreoffice export pdf
# hasEnvVar=`grep 'SAL_VCL_QT5_USE_CAIRO' /etc/environment`
# if [ "$hasEnvVar" == "" ]; then
# 	echo "SAL_VCL_QT5_USE_CAIRO=true" >> /etc/environment
# 	sudo chmod 644 /etc/environment
# fi

# Apport
#sed -i 's/enabled=1/enabled=0/g' /etc/default/apport
#sudo chmod 644 /etc/default/apport

# Cleaning chrome environment
apt autoremove -y
apt autoclean -y
rm -rf ~/.bash_history /tmp/*
rm -rf /var/lib/dbus/machine-id
rm -rf /sbin/initctl
rm -rf /root/.wgetrc
rm -rf /root/.config
rm -rf /var/crash/*
rm -rf /root/.mozilla
dpkg-divert --rename --remove /sbin/initctl

# Unmount specials files and exiting of chroot
while [ ! -z "$(ls -A /proc)" ]; do
	umount /proc
	umount -lf /proc
	sleep 1
done
while [ ! -z "$(ls -A /sys)" ]; do
	umount /sys
	umount -lf /sys
	sleep 1
done
while [ ! -z "$(ls -A /dev/pts)" ]; do
	umount /dev/pts
	umount -lf /dev/pts
	sleep 1
done
