#!/bin/bash

devDependency () {
	STAT="`dpkg-query -W -f='${status}' $1`"
	if [ "$STAT" != "install ok installed" ]; then
		sudo apt install $1 >/dev/null 2>&1
	fi
}

getFileSize () {
	if [ ! -f $1 ]; then echo 0; return; fi
	stat --printf="%s" $1
}

devDependency "wget"
devDependency "zenity"
devDependency "squashfs-tools"
devDependency "xorriso"
