#!/bin/bash

CODENAME=$(cat disk/etc/lsb-release | grep DISTRIB_CODENAME | cut -d '=' -f 2)

hasPartner=$(grep "apt-setup/partner" cache/extract-cd/preseed/lubuntu.seed)
if [ "$hasPartner" == "" ]; then
    sudo sed -i '5i\# Enable archive.canonical.com.'  cache/extract-cd/preseed/lubuntu.seed
    sudo sed -i '6i\d-i     apt-setup/partner   boolean true'  cache/extract-cd/preseed/lubuntu.seed
fi

echo "Deploying mscorefonts"
mkdir -p disk/tmp/mscoref/
sudo cp -rf libs/mscorefonts/*.exe disk/tmp/mscoref/

echo "Deploying Chrome"
sudo mkdir -p -m777 disk/usr/wx-center/modules/Chrome/
sudo cp -rf libs/chrome/google-chrome-stable.deb disk/usr/wx-center/modules/Chrome/
sudo cp -rf modules/Chrome/* disk/usr/wx-center/modules/Chrome/

echo "Deploying VS Code"
sudo mkdir -p -m777 disk/usr/wx-center/modules/VSCode/
sudo cp -rf libs/vscode/visual-studio-code.deb disk/usr/wx-center/modules/VSCode/
sudo cp -rf modules/VSCode/* disk/usr/wx-center/modules/VSCode/

echo "Deploying Master PDF"
sudo mkdir -p -m777 disk/usr/wx-center/modules/MasterPDF/
sudo cp -rf libs/masterPdf/master-pdf-editor.deb disk/usr/wx-center/modules/MasterPDF/
sudo cp -rf modules/MasterPDF/* disk/usr/wx-center/modules/MasterPDF/

echo "Deploying Themes-apply"
sudo mkdir -p -m777 disk/usr/wx-center/modules/Win10Theme/
if [ "$CODENAME" == "bionic" ]; then
    sudo cp -rf libs/themes-apply/lxde-win-theme-apply.deb disk/usr/wx-center/modules/Win10Theme/
else
    sudo cp -rf libs/themes-apply/lubuntu-win-theme-apply.deb disk/usr/wx-center/modules/Win10Theme/
fi

echo "Deploying Unetbootin"
sudo mkdir -p -m777 disk/usr/wx-center/modules/Unetbootin/
if [ "$CODENAME" == "bionic" ]; then
    sudo cp -rf libs/unetbootin/unetbootin-bionic.deb disk/usr/wx-center/modules/Unetbootin/
else
    sudo cp -rf libs/unetbootin/unetbootin-focal.deb disk/usr/wx-center/modules/Unetbootin/
fi
sudo cp -rf modules/Unetbootin/* disk/usr/wx-center/modules/Unetbootin/

echo "Deploying ProxyLinux"
sudo mkdir -p -m777 disk/usr/wx-center/modules/ProxyLinux/
sudo cp -rf modules/ProxyLinux/* disk/usr/wx-center/modules/ProxyLinux/

echo "Deploying Profiles"
sudo rm -rf disk/usr/wx-center/profiles/*
sudo cp -rf modules/profiles/* disk/usr/wx-center/profiles/

echo "Deploying Verify"
sudo cp -rf modules/verify/verify-winunix disk/usr/bin/