#!/bin/bash

mkdir cache -p
ISOPATH="cache/lubuntu20-desk.iso"
if [ ! "$(getFileSize $ISOPATH)" -gt "0" ]; then
	ISO=`zenity --file-selection --title="Select the ISO image" 2>/dev/null`
	echo "Copying $ISO..."
	rsync --info=progress2 "$ISO" "$ISOPATH"
fi

if [ ! -d disk/ ] || [ ! -d cache/extract-cd/ ]; then
    echo "Mounting file .iso in 'mnt' folder."
	mkdir mnt -p
	sudo mount -o loop $ISOPATH mnt >/dev/null 2>&1

    if [ ! -d disk/ ]; then
		echo "Extracting files from system"
		sudo unsquashfs mnt/casper/filesystem.squashfs
		sudo mv squashfs-root disk
	fi

    if [ ! -d cache/extract-cd/ ]; then
		echo "Extracting files from .iso in 'extract-cd' folder"
		mkdir cache/extract-cd/ -p
		sudo rsync --exclude=/casper/filesystem.squashfs -a mnt/ cache/extract-cd/ >/dev/null 2>&1

		echo "Extract the isohybrid MBR isohdpfx.bin from ISO using dd"
		sudo dd if=$ISOPATH bs=512 count=1 of=cache/extract-cd/isolinux/isohdpfx.bin >/dev/null 2>&1
	fi

    sudo umount mnt
	rmdir mnt
fi
